services:
  app:
    container_name: uksolution-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/logs:/app/logs
      - ./frontend/dist:/app/static
    environment:
      - BACKEND_PORT=4014
    ports:
      - "127.0.0.1:4014:4014"
    restart: unless-stopped
    networks:
      - uksolution-net

networks:
  uksolution-net:
    driver: bridge
