version: '3.8'

services:
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/static
    profiles:
      - build
    command: sh -c "cp -r /app/dist/* /static/ && echo 'Frontend built and copied'"

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vprave-app
    volumes:
      - ./backend/logs:/app/logs
      - ./frontend/dist:/app/static
    environment:
      - BACKEND_PORT=4014
    ports:
      - "127.0.0.1:4014:4014"
    restart: unless-stopped
    networks:
      - vprave-net

networks:
  vprave-net:
    driver: bridge
