services:
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/static
    command: sh -c "cp -r /app/dist/* /static/ && echo 'Frontend built and copied'"

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vprave-app
    volumes:
      - ./backend/logs:/app/logs
      - ./frontend/dist:/app/static
    environment:
      - BACKEND_PORT=4014
    network_mode: host
    restart: unless-stopped


networks:
  vprave-net:
    driver: bridge
